version: '3.6'

services:
  mxm-server:
    container_name: mxm-server

    image: mbari/mxm-server:0.9.1

    ports:
      - "8080:8080"
      - "5005:5005"

    environment:
      MXM_EXTERNAL_URL: ${MXM_EXTERNAL_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: "mxm"
      JDBC_URL: "jdbc:postgresql://mxm-postgres/mxm"
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

    depends_on:
      - mxm-postgres
    restart: always

  mxm-postgres:
    container_name: mxm-postgres
    image: mbari/mxm-postgres:0.9.1

    # ports: ["25432:5432"]

    restart: always

    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

    environment:
      # POSTGRES_USER: will trigger the creation of the "mxm" user
      # and the "mxm" database upon initial run of the container:
      POSTGRES_USER: mxm
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
